const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict'),L=require('./review/dist/team_logic.js');
const nodes=new Map();class E{constructor(){this.children=[];this.style={};this.value=''}set id(v){nodes.set(v,this)}append(...v){this.children.push(...v)}replaceChildren(...v){this.children=v}setAttribute(k,v){this.attributes??={};this.attributes[k]=String(v)}removeAttribute(k){delete this.attributes?.[k]}getAttribute(k){return this.attributes?.[k]}focus(){}select(){}showModal(){this.open=true}close(){this.open=false} }
for(const id of ['strategy-tab','partners-tab','strategy-panel','partner-section','delete-troupe','delete-dialog','delete-description','delete-error','delete-cancel','delete-confirm','compare-troupes','compare-dialog','compare-picker','compare-grid','compare-close','compare-card-dialog','compare-card-title','compare-card-image','compare-card-close','share-troupe','share-dialog','share-code','import-code','share-status','share-close','copy-code','import-troupe','troupe-name-dialog','troupe-name-form','troupe-name-title','troupe-name-input','troupe-name-error','troupe-name-cancel','troupe-name-confirm','troupe-heading','faction-filter','saved-troupes','new-troupe','rename-troupe','storage-status','troupe-chart','metric-summary','mini-dialog','mini-title','mini-image','mini-loading','mini-store','mini-close','partners','partner-heading','troupe-faction','find','sort','team','team-status','tag-summary','keyword-summary','notice','catalogue','result-count','focused','filter-fields','clear-filters','load-status']){const e=new E();e.id=id}
nodes.get('sort').value='name';
const cards=JSON.parse(fs.readFileSync('data/characters.json','utf8')),storage=new Map(),promptAnswers=[];
const ctx=vm.createContext({TeamLogic:L,console,TextEncoder,TextDecoder,btoa,atob,document:{getElementById:id=>nodes.get(id),createElement:()=>new E(),createElementNS:()=>new E()},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},fetch:async()=>({ok:true,json:async()=>({cards})})});
const markup=fs.readFileSync(process.argv.includes('--static')?'site/index.html':'review/dist/builder.html','utf8');assert.ok(markup.includes('<details class="filters">'));assert.ok(markup.includes('id="strategy-tab" role="tab"'));assert.ok(markup.includes('id="partners-tab" role="tab"'));assert.ok(!markup.includes('id="troupe-name"'));assert.ok(!markup.includes('id="load-troupe"'));assert.ok(!markup.includes('id="save-troupe"'));assert.ok(!markup.includes('Drag members to reorder.'));assert.match(markup,/<label for="saved-troupes">Troupes<\/label>/);
vm.runInContext(fs.readFileSync(process.argv.includes('--static')?'site/builder.js':'review/dist/builder.js','utf8'),ctx);
function nameDialog(button){if(nodes.get('troupe-name-dialog').open)nodes.get('troupe-name-cancel').onclick();button.onclick();assert.equal(nodes.get('troupe-name-dialog').open,true);const answer=promptAnswers.length?promptAnswers.shift():'New troupe';if(answer===null)nodes.get('troupe-name-cancel').onclick();else{nodes.get('troupe-name-input').value=answer;nodes.get('troupe-name-form').onsubmit({preventDefault(){}})}}
function createTroupe(){nameDialog(nodes.get('new-troupe'))}
function renameTroupe(){nameDialog(nodes.get('rename-troupe'))}
(async()=>{await new Promise(r=>setImmediate(r));assert.equal(vm.runInContext('cards.length',ctx),141);assert.ok(nodes.get('catalogue').children.every(n=>!n.className.includes('incompatible')));assert.equal(nodes.get('catalogue').children.length,141);assert.equal(nodes.get('team').children.length,6);assert.ok(!nodes.has('faction')&&!nodes.has('size')&&!nodes.has('troupe-name'));assert.ok(nodes.get('rename-troupe').disabled);assert.equal(vm.runInContext('savedTroupes.length',ctx),0);assert.ok(!nodes.get('focused').children.some(n=>n.className==='panel'));
 const actions=nodes.get('focused').children[0];const miniButton=actions.children.find(n=>n.className==='mini-photo');assert.ok(miniButton);miniButton.onclick();assert.equal(nodes.get('mini-dialog').open,true);assert.equal(nodes.get('mini-image').src,cards[0].miniature.image_url);assert.equal(nodes.get('mini-store').href,cards[0].miniature.store_url);nodes.get('mini-image').onload();assert.equal(nodes.get('mini-image').hidden,false);nodes.get('mini-image').onerror();assert.equal(nodes.get('mini-image').hidden,true);assert.match(nodes.get('mini-loading').textContent,/could not load/);nodes.get('mini-close').onclick();assert.equal(nodes.get('mini-dialog').open,false);miniButton.onclick();nodes.get('mini-dialog').onclick({target:nodes.get('mini-dialog')});assert.equal(nodes.get('mini-dialog').open,false);
 const partnerRows=nodes.get('partners').children.filter(n=>n.className==='partner');assert.equal(partnerRows.length,3);assert.equal(nodes.get('partner-heading').textContent,'Suggested Partners');
 const partnerVisitCount=vm.runInContext('visits.length',ctx);
 partnerRows[0].children[0].children.find(n=>n.className==='partner-add').onclick();assert.equal(vm.runInContext('visits.length',ctx),partnerVisitCount);assert.equal(vm.runInContext('focus.id',ctx),cards[0].id);assert.equal(vm.runInContext('teamIds[0]',ctx),cards[1].id);vm.runInContext('remove(cards[1])',ctx);
 vm.runInContext('add(cards[0]);add(cards[1]);add(cards[0])',ctx);assert.equal(vm.runInContext('teamIds.length',ctx),2);
 assert.ok(nodes.get('keyword-summary').children.some(c=>c.textContent==='Human ×2'));
 vm.runInContext('add(cards[63])',ctx);assert.equal(vm.runInContext('teamIds.length',ctx),2);
 // Faction quick filtering follows the leader and never hides the empty-troupe library.
 assert.equal(nodes.get('load-status').textContent,'');assert.equal(nodes.get('troupe-heading').textContent,'Your Troupe: New troupe');
 assert.equal(nodes.get('faction-filter').attributes['aria-pressed'],'true');assert.ok(nodes.get('catalogue').children.length<141);assert.ok(nodes.get('catalogue').children.every(n=>!n.className.includes('incompatible')));nodes.get('faction-filter').onclick();assert.equal(nodes.get('catalogue').children.length,141);
 // Independent stars, membership ticks, persistence and combined filters.
 const tileFor=c=>nodes.get('catalogue').children.find(n=>n.children[0]?.children[0]?.children[0]?.textContent===c.name);
 const baronTile=tileFor(cards[0]);assert.ok(baronTile.children[0].children[0].children.some(n=>n.className==='troupe-tick'));assert.ok(!baronTile.children.some(n=>n.textContent==='In your troupe'));
 assert.equal(baronTile.children[0].children[0].children.find(n=>n.className==='troupe-tick').title,'In your troupe');assert.ok(nodes.get('tag-summary').children.every(n=>n.title));
 const beforeFavouriteFocus=vm.runInContext('focus.id',ctx),beforeFavouriteVisits=vm.runInContext('visits.length',ctx);let propagationStopped=false;
 baronTile.children[1].children[1].onclick({stopPropagation(){propagationStopped=true}});assert.ok(propagationStopped);assert.equal(vm.runInContext('focus.id',ctx),beforeFavouriteFocus);assert.equal(vm.runInContext('visits.length',ctx),beforeFavouriteVisits);assert.equal(tileFor(cards[0]).children[1].children[1].attributes['aria-pressed'],'true');assert.ok(JSON.parse(storage.get('moonstone-favourites-v1')).includes(cards[0].id));
 const filterRow=field=>nodes.get('filter-fields').children.find(row=>row.children[0].htmlFor==='filter-'+field);
 assert.equal(nodes.get('filter-fields').children.length,vm.runInContext('Object.keys(fields).length',ctx));assert.ok(nodes.get('filter-fields').children.every(row=>row.attributes['data-active']==='false'));
 nodes.get('filter-favourite').checked=true;nodes.get('filter-favourite').onchange();assert.equal(nodes.get('catalogue').children.length,1);assert.equal(filterRow('favourite').attributes['data-active'],'true');
 nodes.get('filter-hp').value=String(vm.runInContext("sliderValues('hp').length",ctx));nodes.get('filter-hp').oninput();assert.match(nodes.get('result-count').textContent,/^0/);filterRow('hp').children[2].onclick();assert.equal(nodes.get('catalogue').children.length,1);assert.equal(filterRow('hp').attributes['data-active'],'false');assert.equal(nodes.get('filter-fields').children.length,vm.runInContext('Object.keys(fields).length',ctx));
 nodes.get('filter-favourite').checked=false;nodes.get('filter-favourite').onchange();assert.equal(nodes.get('catalogue').children.length,141);assert.ok(tileFor(cards[0]));nodes.get('filter-favourite').checked=true;nodes.get('filter-favourite').onchange();tileFor(cards[0]).children[1].children[1].onclick({stopPropagation(){}});assert.match(nodes.get('result-count').textContent,/^0/);
 storage.set('moonstone-favourites-v1',JSON.stringify([cards[0].id,cards[0].id,'unknown',null]));vm.runInContext('favouriteIds=new Set();restoreFavourites()',ctx);assert.equal(vm.runInContext('favouriteIds.size',ctx),1);
 nodes.get('clear-filters').onclick();assert.equal(tileFor(cards[0]).children[1].children[1].textContent,'★');vm.runInContext('toggleFavourite(cards[0])',ctx);
 assert.equal(vm.runInContext('troupeFaction()',ctx),'Commonwealth');assert.ok(tileFor(cards[13]).className.includes('incompatible'));assert.ok(tileFor(cards[13]).children[0].children[0].children.some(n=>n.className==='troupe-incompatible'&&n.title.includes('Commonwealth')));assert.ok(!tileFor(cards[13]).children.some(n=>n.className==='compatibility'));assert.equal(tileFor(cards[13]).children[0].children[0].children.find(n=>n.className==='troupe-incompatible').textContent,'');assert.equal(vm.runInContext('inspectionReason(cards[13],troupeReason(cards[13]))',ctx),'This hero cannot be added to your team. It is not part of the Commonwealth faction.');
 vm.runInContext('remove(cards[0])',ctx);assert.equal(vm.runInContext('teamIds.length',ctx),1);
 assert.equal(JSON.parse(storage.get('moonstone-troupe-v1')).ids.length,1);
 nodes.get('clear-filters').onclick();assert.ok(nodes.get('filter-fields').children.every(row=>row.attributes['data-active']==='false'));
 assert.equal(nodes.get('filter-favourite').type,'checkbox');assert.equal(vm.runInContext('fields.tag',ctx),'Tags');nodes.get('filter-keyword').value='Human';nodes.get('filter-keyword').onchange();nodes.get('filter-keyword2').value='Soldier';nodes.get('filter-keyword2').onchange();assert.equal(nodes.get('catalogue').children.length,cards.filter(c=>c.keywords.includes('Human')&&c.keywords.includes('Soldier')).length);filterRow('keyword2').children[2].onclick();assert.equal(nodes.get('catalogue').children.length,cards.filter(c=>c.keywords.includes('Human')).length);nodes.get('clear-filters').onclick();
 vm.runInContext('show(cards[27])',ctx);assert.match(nodes.get('partners').children[0].textContent,/Commonwealth/);
 vm.runInContext('show(cards[63])',ctx);assert.match(nodes.get('partners').children[0].textContent,/summon support/);
 // Actual browsing, not catalogue order or troupe mutations.
 vm.runInContext('show(cards[137])',ctx);
 const related=()=>nodes.get('focused').children.filter(n=>n.className==='related-characters');
 const pickles=related()[0].children[1].children.find(n=>n.textContent==='Pickles');assert.ok(pickles);pickles.onclick();
 assert.equal(vm.runInContext('focus.id',ctx),cards[138].id);
 const nav=()=>nodes.get('focused').children[0].children.find(n=>n.className==='card-navigation').children;
 assert.equal(nav()[1].disabled,true);nav()[0].onclick();assert.equal(vm.runInContext('focus.id',ctx),cards[137].id);
 assert.equal(nav()[1].disabled,false);nav()[1].onclick();assert.equal(vm.runInContext('focus.id',ctx),cards[138].id);
 nav()[0].onclick();vm.runInContext('show(cards[62])',ctx);assert.equal(nav()[1].disabled,true);
 const before=vm.runInContext('visits.length',ctx);vm.runInContext('remove(cards[1])',ctx);assert.equal(vm.runInContext('visits.length',ctx),before);
 const guide=nodes.get('strategy-panel').children.find(n=>n.className==='strategy-guide');assert.ok(guide);assert.equal(guide.children[0].textContent,'Strategy Summary');nodes.get('partners-tab').onclick();assert.equal(nodes.get('strategy-panel').hidden,true);assert.equal(nodes.get('partner-section').hidden,false);assert.equal(nodes.get('partners-tab').attributes['aria-selected'],'true');nodes.get('strategy-tab').onclick();assert.equal(nodes.get('strategy-panel').hidden,false);
 assert.ok(!nodes.get('focused').children.some(n=>n.textContent==='Card zoom'));assert.ok(!nodes.has('focus-zoom'));
 for(const c of cards){vm.runInContext('show(cards.find(c=>c.id==='+JSON.stringify(c.id)+'),false)',ctx);assert.ok(nodes.get('strategy-panel').children.some(n=>n.className==='strategy-guide'))}
 // Numeric settings are minimums and combine implicitly with AND.
 nodes.get('clear-filters').onclick();nodes.get('filter-hp').value=String(vm.runInContext("sliderValues('hp').indexOf(7)+1",ctx));nodes.get('filter-hp').oninput();nodes.get('filter-energy').value=String(vm.runInContext("sliderValues('energy').indexOf(4)+1",ctx));nodes.get('filter-energy').oninput();assert.equal(nodes.get('catalogue').children.length,cards.filter(c=>c.stats.health>=7&&c.stats.energy>=4).length);nodes.get('filter-energy').value='0';nodes.get('filter-energy').oninput();assert.equal(nodes.get('catalogue').children.length,cards.filter(c=>c.stats.health>=7).length);assert.equal(filterRow('energy').attributes['data-active'],'false');
 nodes.get('clear-filters').onclick();assert.ok(!nodes.has('filter-version')&&!nodes.has('filter-review'));for(const field of ['melee','arcane','evade','range','hp','energy','base']){assert.equal(nodes.get('filter-'+field).type,'range');assert.equal(nodes.get('filter-'+field).step,1)}
 nodes.get('filter-eligibility').checked=true;nodes.get('filter-eligibility').onchange();assert.equal(nodes.get('catalogue').children.length,14);nodes.get('filter-eligibility').checked=false;nodes.get('filter-eligibility').onchange();assert.equal(nodes.get('catalogue').children.length,141);
 // Empty troupes retain a usable catalogue after New and last-member removal.
 nodes.get('clear-filters').onclick();nodes.get('find').value='';createTroupe();assert.equal(nodes.get('catalogue').children.length,141);assert.ok(nodes.get('catalogue').children.every(n=>!n.className.includes('incompatible')));
 vm.runInContext('add(cards[0])',ctx);nodes.get('faction-filter').onclick();vm.runInContext('remove(cards[0])',ctx);assert.ok(nodes.get('faction-filter').disabled);assert.equal(nodes.get('faction-filter').attributes['aria-pressed'],'false');assert.equal(vm.runInContext('teamIds.length',ctx),0);assert.equal(nodes.get('catalogue').children.length,141);assert.equal(nodes.get('team').children.length,6);
 // Named creation auto-saves and selects; cancelling and blank names preserve the draft.
 vm.runInContext('savedTroupes=[];activeTroupeId=null;teamIds=[];updateStorageControls()',ctx);
 promptAnswers.push(null);createTroupe();assert.equal(vm.runInContext('savedTroupes.length',ctx),0);
 promptAnswers.push('   ');createTroupe();assert.equal(vm.runInContext('savedTroupes.length',ctx),0);assert.equal(nodes.get('troupe-name-dialog').open,true);assert.match(nodes.get('troupe-name-error').textContent,/Enter a troupe name/);
 promptAnswers.push('Alpha');createTroupe();const alpha=vm.runInContext('activeTroupeId',ctx);assert.equal(vm.runInContext('savedTroupes.length',ctx),1);assert.equal(nodes.get('saved-troupes').value,alpha);assert.equal(vm.runInContext('troupeName',ctx),'Alpha');assert.equal(nodes.get('troupe-heading').textContent,'Your Troupe: Alpha');assert.equal(nodes.get('storage-status').textContent,'');assert.ok(!nodes.get('rename-troupe').disabled);
 vm.runInContext('add(cards[0]);add(cards[1])',ctx);assert.equal(vm.runInContext('savedTroupes.find(t=>t.id===activeTroupeId).ids.length',ctx),2);
 assert.equal(nodes.get('metric-summary').children.length,6);const radar=nodes.get('troupe-chart').children[0];assert.equal(radar.attributes.role,'img');assert.match(radar.attributes['aria-label'],/Tank.*Damage.*Support.*Moonstone.*Complexity.*Range/);assert.equal(radar.children.filter(n=>n.attributes?.class==='radar-grid').length,5);
 promptAnswers.push('Beta');createTroupe();vm.runInContext('add(cards[2])',ctx);assert.equal(vm.runInContext('savedTroupes.length',ctx),2);
 nodes.get('saved-troupes').value=alpha;nodes.get('saved-troupes').onchange();assert.equal(vm.runInContext('troupeName',ctx),'Alpha');assert.equal(nodes.get('troupe-heading').textContent,'Your Troupe: Alpha');assert.equal(vm.runInContext('teamIds.length',ctx),2);
 promptAnswers.push('Renamed Alpha');renameTroupe();assert.equal(vm.runInContext('savedTroupes.length',ctx),2);assert.equal(vm.runInContext('savedTroupes.find(t=>t.id===activeTroupeId).name',ctx),'Renamed Alpha');assert.equal(nodes.get('storage-status').textContent,'');
 promptAnswers.push(null);renameTroupe();assert.equal(vm.runInContext('troupeName',ctx),'Renamed Alpha');assert.equal(nodes.get('troupe-heading').textContent,'Your Troupe: Renamed Alpha');
 vm.runInContext('remove(cards[1])',ctx);assert.equal(vm.runInContext('savedTroupes.find(t=>t.id===activeTroupeId).ids.length',ctx),1);
 vm.runInContext('teamIds=[];savedTroupes=[];activeTroupeId=null;restoreTroupes()',ctx);assert.equal(vm.runInContext('teamIds.length',ctx),1);assert.equal(vm.runInContext('savedTroupes.length',ctx),2);assert.equal(vm.runInContext('troupeName',ctx),'Renamed Alpha');assert.equal(nodes.get('troupe-heading').textContent,'Your Troupe: Renamed Alpha');
 createTroupe();assert.equal(vm.runInContext('L.troupeMetrics(members()).Tank',ctx),0);
 storage.delete('moonstone-troupes-v2');storage.set('moonstone-troupe-v1',JSON.stringify({ids:[cards[0].id,cards[0].id,cards[63].id,'gone'],faction:'Commonwealth',size:5}));vm.runInContext('savedTroupes=[];activeTroupeId=null;restoreTroupes()',ctx);assert.equal(vm.runInContext('teamIds.length',ctx),1);assert.equal(vm.runInContext('troupeFaction()',ctx),'Commonwealth');assert.equal(vm.runInContext('troupeSnapshot().size',ctx),6);assert.ok(nodes.get('rename-troupe').disabled);
 // Native dragging, keyboard ordering, derived faction and saved slot order.
 createTroupe();vm.runInContext('add(cards[27]);add(cards[0]);add(cards[1])',ctx);assert.equal(vm.runInContext('troupeFaction()',ctx),'Commonwealth');
 const dragFocus=vm.runInContext('focus.id',ctx),dragHistory=vm.runInContext('visits.length',ctx),startRow=nodes.get('team').children[2],targetRow=nodes.get('team').children[0];
 const transfer={setData(){},effectAllowed:'',dropEffect:''};startRow.ondragstart({dataTransfer:transfer});let prevented=false;targetRow.ondragover({dataTransfer:transfer,preventDefault(){prevented=true}});assert.ok(prevented);assert.equal(targetRow.attributes['data-drag-over'],'true');targetRow.ondrop({preventDefault(){}});
 assert.equal(vm.runInContext('teamIds[0]',ctx),cards[1].id);assert.equal(vm.runInContext('focus.id',ctx),dragFocus);assert.equal(vm.runInContext('visits.length',ctx),dragHistory);assert.equal(nodes.get('team').children.length,6);
 assert.equal(JSON.parse(storage.get('moonstone-troupes-v2')).draft.ids[0],cards[1].id);
 nodes.get('team').children[0].children[1].onkeydown({key:'ArrowDown',preventDefault(){}});assert.equal(vm.runInContext('teamIds[1]',ctx),cards[1].id);
 const ordered=vm.runInContext('activeTroupeId',ctx),orderedIds=JSON.parse(JSON.stringify(vm.runInContext('teamIds',ctx)));createTroupe();nodes.get('saved-troupes').value=ordered;nodes.get('saved-troupes').onchange();assert.deepEqual(JSON.parse(JSON.stringify(vm.runInContext('teamIds',ctx))),orderedIds);
 // A dual-faction leader permits either route; a conflicting saved team is flagged against slot 1.
 createTroupe();vm.runInContext('add(cards[27])',ctx);assert.deepEqual(JSON.parse(JSON.stringify(vm.runInContext('troupeFactions()',ctx))),['Commonwealth','Dominion']);assert.equal(vm.runInContext('troupeReason(cards[13])',ctx),'');vm.runInContext('add(cards[13])',ctx);assert.equal(vm.runInContext('troupeFaction()',ctx),'Dominion');assert.match(vm.runInContext('troupeReason(cards[0])',ctx),/Outside/);
 vm.runInContext('teamIds=[cards[0].id,cards[13].id];repaintTroupe()',ctx);assert.ok(nodes.get('team').children[1].className.includes('incompatible'));vm.runInContext('reorderMember(cards[13].id,0)',ctx);assert.equal(vm.runInContext('troupeFaction()',ctx),'Dominion');assert.ok(nodes.get('team').children[1].className.includes('incompatible'));
 createTroupe();vm.runInContext('for(const c of cards.filter(c=>c.eligibility.selectable&&c.factions.includes("Commonwealth")))if(teamIds.length<6)add(c);',ctx);assert.equal(vm.runInContext('teamIds.length',ctx),6);assert.match(vm.runInContext('troupeReason(cards.find(c=>c.eligibility.selectable&&c.factions.includes("Commonwealth")&&!teamIds.includes(c.id)))',ctx),/full/);
 storage.set('moonstone-troupes-v2','{bad json');vm.runInContext('restoreTroupes()',ctx);assert.match(nodes.get('storage-status').textContent,/could not be read/);
 const beforeFailureId=vm.runInContext('activeTroupeId',ctx),beforeFailureCount=vm.runInContext('savedTroupes.find(t=>t.id===activeTroupeId).ids.length',ctx);ctx.localStorage.setItem=()=>{throw Error('Quota exceeded')};vm.runInContext('remove(members()[0])',ctx);assert.equal(vm.runInContext('savedTroupes.find(t=>t.id===activeTroupeId).ids.length',ctx),beforeFailureCount);assert.match(nodes.get('storage-status').textContent,/unavailable/);
 const failedSwitchIds=JSON.parse(JSON.stringify(vm.runInContext('teamIds',ctx))),otherSwitchId=vm.runInContext('savedTroupes.find(t=>t.id!==activeTroupeId).id',ctx);nodes.get('saved-troupes').value=otherSwitchId;nodes.get('saved-troupes').onchange();assert.equal(vm.runInContext('activeTroupeId',ctx),beforeFailureId);assert.deepEqual(JSON.parse(JSON.stringify(vm.runInContext('teamIds',ctx))),failedSwitchIds);
 ctx.localStorage.setItem=(k,v)=>storage.set(k,v);
 const shared=vm.runInContext('encodeTroupe({name:"The Savages 🌙",ids:[cards[0].id,cards[1].id]})',ctx);ctx.shared=shared;assert.deepEqual(JSON.parse(JSON.stringify(vm.runInContext('decodeTroupe(shared)',ctx))),{name:'The Savages 🌙',ids:[cards[0].id,cards[1].id]});assert.throws(()=>vm.runInContext('decodeTroupe("nonsense")',ctx));ctx.badCode=vm.runInContext('encodeTroupe({name:"Illegal",ids:[cards[0].id,cards[13].id]})',ctx);assert.throws(()=>vm.runInContext('decodeTroupe(badCode)',ctx));for(const ids of [[cards[0].id,cards[0].id],[cards.find(c=>!c.eligibility.selectable).id],Array(7).fill(cards[0].id)]){ctx.invalidIds=ids;ctx.invalidCode=vm.runInContext('encodeTroupe({name:"Invalid",ids:invalidIds})',ctx);assert.throws(()=>vm.runInContext('decodeTroupe(invalidCode)',ctx));}const oldCount=vm.runInContext('savedTroupes.length',ctx);nodes.get('import-code').value='bad';nodes.get('import-troupe').onclick();assert.equal(vm.runInContext('savedTroupes.length',ctx),oldCount);nodes.get('share-troupe').onclick();nodes.get('import-code').value=shared;nodes.get('import-troupe').onclick();assert.equal(vm.runInContext('savedTroupes.length',ctx),oldCount+1);assert.equal(vm.runInContext('troupeName',ctx),'The Savages 🌙');assert.equal(nodes.get('share-dialog').open,false);nodes.get('compare-troupes').onclick();assert.ok(nodes.get('compare-grid').children.length);const importedPanel=nodes.get('compare-grid').children.find(n=>n.children[0].textContent==='The Savages 🌙');assert.ok(importedPanel);importedPanel.children[2].children[0].onclick();assert.equal(nodes.get('compare-card-dialog').open,true);assert.equal(nodes.get('compare-card-title').textContent,cards[0].name);nodes.get('compare-card-close').onclick();assert.equal(nodes.get('compare-dialog').open,true);
 const deleteCount=vm.runInContext('savedTroupes.length',ctx);nodes.get('delete-troupe').onclick();assert.equal(nodes.get('delete-dialog').open,true);nodes.get('delete-cancel').onclick();assert.equal(vm.runInContext('savedTroupes.length',ctx),deleteCount);nodes.get('delete-troupe').onclick();ctx.localStorage.setItem=()=>{throw Error('Quota')};nodes.get('delete-confirm').onclick();assert.equal(vm.runInContext('savedTroupes.length',ctx),deleteCount);assert.match(nodes.get('delete-error').textContent,/Nothing was deleted/);ctx.localStorage.setItem=(k,v)=>storage.set(k,v);const deletedId=vm.runInContext('activeTroupeId',ctx);nodes.get('delete-confirm').onclick();assert.equal(vm.runInContext('savedTroupes.length',ctx),deleteCount-1);assert.ok(!JSON.parse(storage.get('moonstone-troupes-v2')).troupes.some(t=>t.id===deletedId));while(vm.runInContext('savedTroupes.length',ctx)){nodes.get('delete-troupe').onclick();nodes.get('delete-confirm').onclick()}assert.equal(nodes.get('delete-troupe').disabled,true);assert.equal(nodes.get('rename-troupe').disabled,true);assert.equal(vm.runInContext('teamIds.length',ctx),0);vm.runInContext('restoreTroupes()',ctx);assert.equal(vm.runInContext('teamIds.length',ctx),0);
 console.log('Builder state checks passed: add/remove, duplicate/summon rejection, summaries, automatic faction, drag/keyboard ordering, saved troupes, migration, radar averages, favourites and filters.');
})().catch(e=>{console.error(e);process.exitCode=1});
